### ISSUE TITLE
Integration of VMV format into vascpy

### ISSUE THREAD

**Issue by marwan-abdellah** [BlueBrain/vascpy#12]
We have several datasets in [VMV format](https://github.com/BlueBrain/VessMorphoVis/wiki/File-Formats) that are used by external collaborators. Would it be possible that we can make this format part of the tool?

**Comment by eleftherioszisis** [comment]
Hi Marwan,

As we agreed in person, it would be preferable to convert the existing data in VMV format into the binary HDF5, which is supported by `vascpy`.

The VMV format was a temporary solution in place of the binary one before the latter became open-sourced and being an ascii format makes it less than ideal for large datasets.

Please feel free to open a PR with a script for the conversion.
